[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "esycord"
version = "0.1"

dependencies = ["discord==2.3.2", "aiohttp==3.9.5"]
requires-python = ">3.8"

authors =[
    { name = "Aayush Srivastava", discord = "aayush.2410"}
    ]

description = "The most beginner friendly discord package"
readme = {file = "README.md", content-type = "text/markdown"}

keywords = ["discord", "beginner discord", "easycord", "discord simple"]

license = "MIT"

